name: Build Windows Executable

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch
  pull_request:
    branches:
      - main  # Trigger build on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up a Python environment
      with:
        python-version: '3.10'  # Use Python 3.10, compatible with PyQt5==5.15.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile main.py  # Correct command without inline comment
      shell: cmd

    - name: Upload executable
      uses: actions/upload-artifact@v3  # Upload the generated .exe file as an artifact using v3
      with:
        name: oneplus7pro-tool  # Name of the uploaded artifact
        path: dist/main.exe  # Path to the .exe file in the dist directory created by PyInstaller
