name: Build Windows Installer

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch
  pull_request:
    branches:
      - main  # Trigger build on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up a Python environment
      with:
        python-version: '3.10'  # Use Python 3.10, compatible with PyQt5==5.15.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile main.py

    - name: Download Inno Setup
      run: |
        curl -L -o innosetup.exe https://jrsoftware.org/download.php/is.exe  # Download Inno Setup installer

    - name: Install Inno Setup
      run: |
        .\innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-  # Install Inno Setup silently
      shell: cmd

    - name: Create Inno Setup script
      run: |
        echo [Setup] > installer.iss
        echo AppName=OnePlus 7 Pro Tool >> installer.iss
        echo AppVersion=1.0 >> installer.iss
        echo DefaultDirName={autopf}\\OnePlus 7 Pro Tool >> installer.iss
        echo OutputDir=dist >> installer.iss
        echo OutputBaseFilename=OnePlus7Pro_Tool_Installer >> installer.iss
        echo [Files] >> installer.iss
        echo Source: "dist\\main.exe"; DestDir: "{app}"; Flags: ignoreversion >> installer.iss
        echo [Icons] >> installer.iss
        echo Name: "{group}\\OnePlus 7 Pro Tool"; Filename: "{app}\\main.exe" >> installer.iss
        echo [Run] >> installer.iss
        echo Filename: "{app}\\main.exe"; Description: "Launch OnePlus 7 Pro Tool"; Flags: nowait postinstall skipifsilent >> installer.iss

    - name: Build Installer with Inno Setup
      run: |
        "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" installer.iss  # Compile the installer
      shell: cmd

    - name: Upload installer
      uses: actions/upload-artifact@v3
      with:
        name: oneplus7pro-tool-installer
        path: dist/OnePlus7Pro_Tool_Installer.exe
