name: Build and Test Windows Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-qt py  # Removed pytest-memory-profiler

    # Run Unit Tests
    - name: Run Unit Tests
      run: |
        python -m pytest tests/unit --disable-warnings --maxfail=1
      shell: bash

    # Run GUI Tests
    - name: Run GUI Tests
      run: |
        python -m pytest tests/gui --disable-warnings --maxfail=1
      shell: bash

    # Build executable with PyInstaller including debug logs
    - name: Build executable with PyInstaller (with debugging)
      run: |
        pyinstaller --onefile --log-level=DEBUG main.py
      shell: bash

    # Run the .exe file and capture output for debugging
    - name: Run the .exe and capture output (for debugging)
      run: |
        dist\\main.exe > exe_output.log 2>&1 || echo "Execution failed, check logs."
      shell: cmd

    # Upload log files for debugging
    - name: Upload log files for debugging
      uses: actions/upload-artifact@v3
      with:
        name: exe-output-log
        path: exe_output.log

    # Inno Setup for building installer
    - name: Download Inno Setup
      run: |
        curl -L -o innosetup.exe https://jrsoftware.org/download.php/is.exe
      shell: bash

    - name: Install Inno Setup
      run: |
        .\innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
      shell: cmd

    # Create the Inno Setup script for building the installer
    - name: Create Inno Setup script
      run: |
        echo "[Setup]" > installer.iss
        echo "AppName=OnePlus 7 Pro Tool" >> installer.iss
        echo "AppVersion=1.0" >> installer.iss
        echo "DefaultDirName={autopf}\\OnePlus 7 Pro Tool" >> installer.iss
        echo "OutputDir=dist" >> installer.iss
        echo "OutputBaseFilename=OnePlus7Pro_Tool_Installer" >> installer.iss
        echo "[Files]" >> installer.iss
        echo "Source: \"dist\\main.exe\"; DestDir: \"{app}\"; Flags: ignoreversion" >> installer.iss
        echo "[Icons]" >> installer.iss
        echo "Name: \"{group}\\OnePlus 7 Pro Tool\"; Filename: \"{app}\\main.exe\"" >> installer.iss
        echo "[Run]" >> installer.iss
        echo "Filename: \"{app}\\main.exe\"; Description: \"Launch OnePlus 7 Pro Tool\"; Flags: nowait postinstall skipifsilent" >> installer.iss
      shell: bash

    # Build the installer with Inno Setup
    - name: Build Installer with Inno Setup
      run: |
        "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" /Q installer.iss
      shell: cmd

    # Upload the generated installer
    - name: Upload installer
      uses: actions/upload-artifact@v3
      with:
        name: oneplus7pro-tool-installer
        path: dist/OnePlus7Pro_Tool_Installer.exe
