name: Build and Test Windows Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-qt pytest-xdist py

    - name: List test files for debugging
      run: |
        ls -R tests
      shell: bash

    # Update to run tests sequentially for better memory usage
    - name: Run Unit Tests
      run: |
        python -m pytest tests --disable-warnings --maxfail=1
      shell: bash

    - name: Build executable with PyInstaller (Debug Mode)
      run: |
        pyinstaller --onefile --debug=all main.py

    - name: Run the .exe and capture console output
      run: |
        ./dist/main.exe > output.log 2>&1 || echo "The app crashed"
      shell: bash

    - name: Upload output log
      uses: actions/upload-artifact@v3
      with:
        name: console-output
        path: output.log

    - name: Download Inno Setup
      run: |
        curl -L -o innosetup.exe https://jrsoftware.org/download.php/is.exe

    - name: Install Inno Setup
      run: |
        .\innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
      shell: cmd

    - name: Create Inno Setup script
      run: |
        echo "[Setup]" > installer.iss
        echo "AppName=OnePlus 7 Pro Tool" >> installer.iss
        echo "AppVersion=1.0" >> installer.iss
        echo "DefaultDirName={autopf}\\OnePlus 7 Pro Tool" >> installer.iss
        echo "OutputDir=dist" >> installer.iss
        echo "OutputBaseFilename=OnePlus7Pro_Tool_Installer" >> installer.iss
        echo "[Files]" >> installer.iss
        echo "Source: \"dist\\main.exe\"; DestDir: \"{app}\"; Flags: ignoreversion" >> installer.iss
        echo "[Icons]" >> installer.iss
        echo "Name: \"{group}\\OnePlus 7 Pro Tool\"; Filename: \"{app}\\main.exe\"" >> installer.iss
        echo "[Run]" >> installer.iss
        echo "Filename: \"{app}\\main.exe\"; Description: \"Launch OnePlus 7 Pro Tool\"; Flags: nowait postinstall skipifsilent" >> installer.iss
      shell: bash

    - name: Build Installer with Inno Setup
      if: success()
      run: |
        "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" /Q installer.iss
      shell: cmd

    - name: Upload installer
      uses: actions/upload-artifact@v3
      with:
        name: oneplus7pro-tool-installer
        path: dist/OnePlus7Pro_Tool_Installer.exe