name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Adjust the Python version as necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller  # Ensure PyInstaller is installed

    - name: Build executable with PyInstaller
      run: |
        pyinstaller main.py --onefile --windowed --name "flash_tool"
      
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flash_tool_exe
        path: dist/flash_tool.exe

    - name: Display executable location
      run: |
        echo "Executable created at: dist/flash_tool.exe"