name: Build and Output Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for building .exe with PyInstaller

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build the executable with PyInstaller
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile main.py

    # Upload the .exe file to the repository as an artifact
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: oneplus7pro-tool-executable
        path: dist/main.exe
